# https://taskfile.dev

version: "2"

tasks:
  validate:
    desc: Validate the pre-commit hooks
    cmds:
      - pre-commit install
      - pre-commit run -a

  test:
    desc: Run automated tests
    cmds:
      - echo "N/A for now. TODO: Use TerraTest"

  secure:
    desc: Run automated security checks
    cmds:
      - echo "N/A. The validate task runs tfsec"

  deliver:
    desc: Deliver artifact
    cmds:
      - echo "N/A. This project does not have a deliverable artifact"

  deploy:
    desc: Deploy project
    cmds:
      - echo "N/A. This project is an example only and does not support a persistent live deployment."
